# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ian J. Frosst
author: Ian J. Frosst
email: ijfrosst@uwaterloo.ca
description: >
    Mechatronics Engineering student at the University of Waterloo.
    Passionate about robotics, embedded systems, and music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ianjfrosst.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ianjfrosst
linkedin_username: ianjfrosst
twitter_username: ianjfrosst
rss: subscribe

include:
    - _pages

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md

header_pages:
    - _pages/about.md
    - _pages/index.md

show_excerpts: true

#google_analytics: UA-NNNNNNNN-N

sass:
    style: compressed

theme: minima

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
    date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
